### ISSUE TITLE
Request Money

### ISSUE THREAD

**Issue by Reaper45** [lipisha/lipisha-node-sdk#4]
Why isn't there a request money method in the lib? Was it left out intentionally?

**Comment by yespbs** [comment]
I want it too.

**Comment by Reaper45** [comment]
@yespbs coming to your rescue in just bit

**Comment by yespbs** [comment]
Git is updated but NPM is not, I have spoke to Lipisha Team

**Comment by Reaper45** [comment]
Oh yeah, found the method. 
`
    this.request_money = function(account_number, mobile_number, method, amount, reference, callback) {
        var parameters = {
            "account_number": account_number,
            "mobile_number": mobile_number,
            "method": method,
            "amount": amount,
            "reference": reference
        };
        this.execute("request_money", parameters, function(err, response) {
            return callback(err, response);
        });
    };
`
